### ISSUE TITLE
C++?

### ISSUE THREAD

**Issue by czycha** [EVA-01/pxlsrt#4]
Would this be better if it were implemented in C++?

**Pros**
- Performance gains: larger images in less time.
- Could use multiple image libraries to remove the strict PNG rule.
- Might be able to pair program with a GUI.

**Cons**
- Cross-platform compatibility will suck.
- Complex and error-prone installation process might scare away potential users.
  - However, distributing over something like Homebrew/APT might prevent this for macOS/Linux users.

**Comment by saadsouls** [comment]
I would recommend C++ definately as it is Computer Friendly hence will give a much better output! 

If you need any help feel free to contact me at saad.souls@gmail.com

Happy Coding!
