### ISSUE TITLE
chunky_png error

### ISSUE THREAD

**Issue by 13um45** [EVA-01/pxlsrt#5]
Hello, I keep running into this error when trying to pixel sort an image: 

```ruby
chunky_png/canvas/png_decoding.rb:120:in `decode_png_image_pass': wrong number of arguments (7 for 6) (ArgumentError)
```
An issue was raised in the chunky_png repo: https://github.com/wvanbergen/chunky_png/issues/114

I was able to resolve the issue by setting oily_png to version 1.2.1 in the gemspec.

**Comment by czycha** [comment]
Thanks for bringing this to my attention!

**Comment by 13um45** [comment]
No problem
